name: Node.js CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Yarn 세팅
    - name: Set up Yarn
      run: npm install -g yarn

    # 라이브러리 설치
    - name: Install Libraries
      run: yarn install

    # .env 파일 생성
    - name: Generate Environment Variables File for Production
      run: |
        echo "$DOT_ENV" >> ./.env
      env:
        DOT_ENV: ${{ secrets.DOT_ENV }}

    # build 실행
    - name: execute build
      run: yarn build

    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy

    # Jar 파일 복사
    - name: Copy dist Directory
      run: cp -r ./dist/ ./deploy

    # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp ./appspec.yml ./deploy

    # deploy.sh 파일 복사
    - name: Copy deploy.sh
      run: cp ./scripts/deploy.sh ./deploy

    # healthCheck.sh 파일 복사
    - name: Copy healthCheck.sh
      run: cp ./scripts/healthCheck.sh ./deploy

    # zip 파일 생성
    - name: Make zip file
      run: zip -r ./footbolic-web.zip ./deploy
      shell: bash

    # AWS 접근 환경설정
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    # Amazon S3에 업로드
    - name: Upload to S3
      run: aws s3 cp ./footbolic-web.zip s3://footbolic-bucket-web

    # CodeDeploy 실행
    - name: Execute CodeDeploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
          --application-name footbolic-web-code-deploy-application \
          --deployment-group-name FOOTBOLIC-WEB-CD-GROUP \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=footbolic-bucket-web,bundleType=zip,key=footbolic-web.zip \
          --region ap-northeast-2